apiVersion: v1
kind: Service
metadata:
  name: staging-ingress-proxy
  annotations:
    cloud.google.com/backend-config: '{"default":"staging-ingress-backend-config"}'
    cloud.google.com/neg: '{"ingress":true}'
spec:
  type: ClusterIP
  selector:
    app: staging-ingress-proxy
  ports:
    - port: 80
      targetPort: 8080
