apiVersion: v1
kind: ConfigMap
metadata:
  name: frontend-config
data:
  NEXT_PUBLIC_API_URL: "/api/v1"
  NEXT_PUBLIC_FIREBASE_API_KEY: ""
  NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN: ""
  NEXT_PUBLIC_FIREBASE_PROJECT_ID: ""
  NEXT_PUBLIC_CENTRIFUGO_URL: "ws://centrifugo:8000/connection/websocket"
