apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: app-ingress
  annotations:
    kubernetes.io/ingress.class: gce
    kubernetes.io/ingress.global-static-ip-name: eval-prod-ingress-ip
    networking.gke.io/managed-certificates: eval-delquillan-com
    networking.gke.io/v1beta1.FrontendConfig: https-redirect
spec:
  defaultBackend:
    service:
      name: frontend
      port:
        number: 80
  rules:
    # Production: eval.delquillan.com
    - host: eval.delquillan.com
      http:
        paths:
          - path: /api/*
            pathType: ImplementationSpecific
            backend:
              service:
                name: go-api
                port:
                  number: 80
          - path: /connection/websocket
            pathType: ImplementationSpecific
            backend:
              service:
                name: centrifugo
                port:
                  number: 8000
          - path: /*
            pathType: ImplementationSpecific
            backend:
              service:
                name: frontend
                port:
                  number: 80
    # Staging: staging.eval.delquillan.com -> staging-ingress-proxy
    - host: staging.eval.delquillan.com
      http:
        paths:
          - path: /*
            pathType: ImplementationSpecific
            backend:
              service:
                name: staging-ingress-proxy
                port:
                  number: 80
