apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - deployment.yaml
  - service.yaml
  - pod-monitoring.yaml
  - executor-deployment.yaml
  - executor-service.yaml
  - executor-configmap.yaml

images:
  - name: go-api
    newName: go-api
  - name: executor
    newName: executor
