apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: staging

resources:
  - ../../base

patches:
  - path: patches/resources.yaml
  - path: patches/executor-resources.yaml
  - path: patches/remove-ingress.yaml
  - path: patches/remove-managed-cert.yaml
  - path: patches/remove-frontend-config.yaml
  - path: patches/remove-backend-config.yaml
  - path: patches/executor-redis-host.yaml
  - path: patches/disable-keda.yaml
  - path: patches/executor-replicas.yaml
  - path: patches/workload-identity.yaml

images:
  - name: go-api
    newName: go-api
  - name: executor
    newName: executor
  - name: frontend
    newName: frontend
  - name: centrifugo/centrifugo
    newName: centrifugo/centrifugo
